# docker pull node:lts
FROM node:lts

# Install necessary tools
RUN apt-get update && apt-get install -y git

# Clone your repository
#  Cursor autocompleted this... i wonder if it is a leaked private repo
#  RUN git clone https://github.com/jake-b/ai_cmd_line_tool.git /ai_cmd_line_tool

#todo migrate to ai_cmd
RUN git clone https://github.com/bcwaters/ai_cmd.git /ai_cmd

# Set the working directory
WORKDIR /ai_cmd

RUN npm install



COPY shell_helpers/.docker_grokRuntime shell_helpers/.grokRuntime
COPY .env .env

# sudo docker build -t ai_cmd -f ./DockerFile .
# sudo docker run -it --name diagnostic-container ai_cmd /bin/bash

# Specify the command to run on container start
# start grok.sh